name: docker build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: tubearchivist-pruner:${{ github.sha }}
          outputs: type=docker,dest=${{ runner.temp }}/tubearchivist-pruner.tar
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: tubearchivist-pruner-image-${{ github.sha }}
          path: ${{ runner.temp }}/tubearchivist-pruner.tar
          retention-days: 30
          compression-level: 0
